//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueTrackingService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Issue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Issue()
        {
            this.Comments = new HashSet<Comment>();
        }
    
        public System.Guid Id { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.Guid ProjectId { get; set; }
        public System.DateTime ProjectCreatedAt { get; set; }
        public System.Guid StateId { get; set; }
        public System.Guid ReporterId { get; set; }
        public Nullable<System.Guid> AssigneeId { get; set; }
        public bool Active { get; set; }
        public int Type { get; set; }
        public string Name { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> ResolvedAt { get; set; }
        public string Description { get; set; }
        public int CodeNumber { get; set; }
        public string Status { get; set; }
        public string Priority { get; set; }
        public string Attachment { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual Project Project { get; set; }
        public virtual State State { get; set; }
    }
}
