//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueTrackingService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project_X_Users
    {
        public System.Guid Id { get; set; }
        public System.Guid AspNetUsersId { get; set; }
        public System.Guid ProjectId { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public bool Active { get; set; }
    }
}
